### ISSUE TITLE
Group Chat Enhancements

### ISSUE THREAD

**Issue by asleepingpanda** [christfellowshipchurch/apollos-app#192] opened 2020-11-05 14:39 UTC
Hey! Noticed 2 things real quick about the Group Chat

1. Profile Photos are not loading
2. On Android, the text field is getting cut behind the Keyboard when focused

![ezgif com-gif-maker](https://user-images.githubusercontent.com/45076058/98254855-c51d3a00-1f4a-11eb-8421-989a1282127f.gif)

**Comment by jordanwade** [comment] 2020-12-11 15:15
@asleepingpanda did you see the profile image issue on a physical device? They seem to be working on my simulator.
![image](https://user-images.githubusercontent.com/2528817/101920367-53f82480-3b91-11eb-9d90-3d27261ca551.png)

**Comment by jordanwade** [comment] 2020-12-11 23:52
Also, I tried to figure out what the problem is with the keyboard with no luck. If anyone has any experience with the `KeyboardAvoider` I would appreciate any insist on any known issues with it.

**Comment by rkdavidson** [comment] 2020-12-14 15:53
I can take a peak at the `<MessageInput>` text clipping issue, though not super optimistic it'll be a quick win.
Looks like Android is properly adjusting to "dock" against the _baseline_ of the text, but agreed it'd be nicer if it snapped to the bottom of the gray outer shape.

Can also see if the padding/vertical centering is a quick fix.

**Comment by rkdavidson** [comment] 2021-04-26 20:39
Closing since we probably fixed or obviated this during CF 6.0 release.

**Closed** 2021-04-26 20:40 UTC
Labels: bug
